import { fisherYatesShuffle } from "./fisherYatesShuffle";
import { PromptCard } from "./types";

export async function fetchPromptCard(): Promise<PromptCard> {
    return fetchFakePromptCard();
}

const FAKE_PROMPT_CARDS: PromptCard[] = [
    { id: "prompt-001", type: "prompt", text: "The worst thing to hear during a job interview is ____." },
    { id: "prompt-002", type: "prompt", text: "My secret superpower is ____." },
    { id: "prompt-003", type: "prompt", text: "The most awkward small talk topic is ____." },
    { id: "prompt-004", type: "prompt", text: "At my funeral, someone will definitely mention ____." },
    { id: "prompt-005", type: "prompt", text: "The best way to ruin a surprise party is ____." },
    { id: "prompt-006", type: "prompt", text: "My phone autocorrected ____ and now I have to change my name." },
    { id: "prompt-007", type: "prompt", text: "The official mascot of my hometown is ____." },
    { id: "prompt-008", type: "prompt", text: "The least inspiring motivational poster says ____." },
    { id: "prompt-009", type: "prompt", text: "The worst thing to find in your couch is ____." },
    { id: "prompt-010", type: "prompt", text: "The real reason the dinosaurs disappeared was ____." },
    { id: "prompt-011", type: "prompt", text: "My therapist says I need to stop talking about ____." },
    { id: "prompt-012", type: "prompt", text: "The first line of my autobiography is ____." },
    { id: "prompt-013", type: "prompt", text: "The fastest way to lose friends is ____." },
    { id: "prompt-014", type: "prompt", text: "I never leave the house without ____." },
    { id: "prompt-015", type: "prompt", text: "The worst theme for a wedding is ____." },
    { id: "prompt-016", type: "prompt", text: "The least helpful emergency contact is ____." },
    { id: "prompt-017", type: "prompt", text: "The most confusing sign in a store says ____." },
    { id: "prompt-018", type: "prompt", text: "My greatest fear is accidentally ordering ____." },
    { id: "prompt-019", type: "prompt", text: "In the future, history class will focus on ____." },
    { id: "prompt-020", type: "prompt", text: "The worst thing to say on a first date is ____." },
    { id: "prompt-021", type: "prompt", text: "The secret ingredient in grandma's recipe is ____." },
    { id: "prompt-022", type: "prompt", text: "My last Google search was ____." },
    { id: "prompt-023", type: "prompt", text: "The official sport of my living room is ____." },
    { id: "prompt-024", type: "prompt", text: "I knew it was time to leave when I saw ____." },
    { id: "prompt-025", type: "prompt", text: "The best name for a pet rock is ____." },
    { id: "prompt-026", type: "prompt", text: "The least impressive party trick is ____." },
    { id: "prompt-027", type: "prompt", text: "I should not have trusted the ____." },
    { id: "prompt-028", type: "prompt", text: "My personal brand is basically ____." },
    { id: "prompt-029", type: "prompt", text: "The worst thing to hear from a GPS is ____." },
    { id: "prompt-030", type: "prompt", text: "The most suspicious thing in my fridge is ____." },
    { id: "prompt-031", type: "prompt", text: "The title of my canceled reality show is ____." },
    { id: "prompt-032", type: "prompt", text: "The last thing I want to see on my resume is ____." },
    { id: "prompt-033", type: "prompt", text: "The most overrated magic spell is ____." },
    { id: "prompt-034", type: "prompt", text: "My neighbors think I'm really into ____." },
    { id: "prompt-035", type: "prompt", text: "The worst thing to spill on yourself is ____." },
    { id: "prompt-036", type: "prompt", text: "I knew the meeting was doomed when ____." },
    { id: "prompt-037", type: "prompt", text: "The most cursed emoji is ____." },
    { id: "prompt-038", type: "prompt", text: "The least fun ride at the theme park is ____." },
    { id: "prompt-039", type: "prompt", text: "My doctor told me to avoid ____." },
    { id: "prompt-040", type: "prompt", text: "The weirdest thing to clap for is ____." },
    { id: "prompt-041", type: "prompt", text: "The best thing to shout in a library is ____." },
    { id: "prompt-042", type: "prompt", text: "My pet's LinkedIn headline is ____." },
    { id: "prompt-043", type: "prompt", text: "The most dramatic way to enter a room is ____." },
    { id: "prompt-044", type: "prompt", text: "The least effective password is ____." },
    { id: "prompt-045", type: "prompt", text: "The worst thing to see on a cake is ____." },
    { id: "prompt-046", type: "prompt", text: "The most confusing fortune cookie says ____." },
    { id: "prompt-047", type: "prompt", text: "The last thing I expected from a magician was ____." },
    { id: "prompt-048", type: "prompt", text: "My new diet forbids ____." },
    { id: "prompt-049", type: "prompt", text: "The most awkward office award is ____." },
    { id: "prompt-050", type: "prompt", text: "The worst thing to hear from tech support is ____." },
    { id: "prompt-051", type: "prompt", text: "The secret level in life unlocks ____." },
    { id: "prompt-052", type: "prompt", text: "The most intense yoga pose is ____." },
    { id: "prompt-053", type: "prompt", text: "My villain origin story starts with ____." },
    { id: "prompt-054", type: "prompt", text: "The least appealing scent is ____." },
    { id: "prompt-055", type: "prompt", text: "The most suspicious checkbox is ____." },
    { id: "prompt-056", type: "prompt", text: "The worst phrase to whisper is ____." },
    { id: "prompt-057", type: "prompt", text: "The most confusing map includes ____." },
    { id: "prompt-058", type: "prompt", text: "The only thing my brain can remember is ____." },
    { id: "prompt-059", type: "prompt", text: "My dream vacation includes ____." },
    { id: "prompt-060", type: "prompt", text: "The least helpful weather forecast predicts ____." },
    { id: "prompt-061", type: "prompt", text: "The worst thing to hear from a waiter is ____." },
    { id: "prompt-062", type: "prompt", text: "The most dramatic text message ends with ____." },
    { id: "prompt-063", type: "prompt", text: "The most boring superpower is ____." },
    { id: "prompt-064", type: "prompt", text: "The least convincing alibi involves ____." },
];

export async function fetchFakePromptCard(): Promise<PromptCard> {
    return fisherYatesShuffle(FAKE_PROMPT_CARDS)[0];
}