import { fisherYatesShuffle } from "./fisherYatesShuffle";
import { AnswerCard } from "./types";

export async function fetchAnswerDeck(): Promise<AnswerCard[]> {
    throw new Error("Not implemented");
}

const FAKE_ANSWER_CARDS: AnswerCard[] = [
    { id: "answer-001", type: "answer", text: "A sad trombone." },
    { id: "answer-002", type: "answer", text: "An unexpected boner." },
    { id: "answer-003", type: "answer", text: "A lifetime of regret." },
    { id: "answer-004", type: "answer", text: "The Pope's Wi-Fi password." },
    { id: "answer-005", type: "answer", text: "A mime having a stroke." },
    { id: "answer-006", type: "answer", text: "Two raccoons in a trench coat." },
    { id: "answer-007", type: "answer", text: "Gluten-free sadness." },
    { id: "answer-008", type: "answer", text: "My browser history." },
    { id: "answer-009", type: "answer", text: "A slow clap that gets out of hand." },
    { id: "answer-010", type: "answer", text: "A tiny horse with big dreams." },
    { id: "answer-011", type: "answer", text: "The smell of Axe body spray." },
    { id: "answer-012", type: "answer", text: "A kazoo solo." },
    { id: "answer-013", type: "answer", text: "Grandma's secret drawer." },
    { id: "answer-014", type: "answer", text: "An army of ducks." },
    { id: "answer-015", type: "answer", text: "A burrito that fights back." },
    { id: "answer-016", type: "answer", text: "The urge to text your ex." },
    { id: "answer-017", type: "answer", text: "A cursed group chat." },
    { id: "answer-018", type: "answer", text: "Pants with no pockets." },
    { id: "answer-019", type: "answer", text: "The last slice of pizza." },
    { id: "answer-020", type: "answer", text: "A dramatic hair flip." },
    { id: "answer-021", type: "answer", text: "An off-brand superhero." },
    { id: "answer-022", type: "answer", text: "A haunted Roomba." },
    { id: "answer-023", type: "answer", text: "Three kids in a hoodie." },
    { id: "answer-024", type: "answer", text: "A karaoke disaster." },
    { id: "answer-025", type: "answer", text: "The weird kid from middle school." },
    { id: "answer-026", type: "answer", text: "A suspiciously moist handshake." },
    { id: "answer-027", type: "answer", text: "A very real fear of clowns." },
    { id: "answer-028", type: "answer", text: "A puppet that knows too much." },
    { id: "answer-029", type: "answer", text: "An awkward silence." },
    { id: "answer-030", type: "answer", text: "Hot sauce in all the wrong places." },
    { id: "answer-031", type: "answer", text: "A skeleton in skinny jeans." },
    { id: "answer-032", type: "answer", text: "The second season nobody asked for." },
    { id: "answer-033", type: "answer", text: "A canceled podcast." },
    { id: "answer-034", type: "answer", text: "A bag of mysterious gummies." },
    { id: "answer-035", type: "answer", text: "A tiny violin." },
    { id: "answer-036", type: "answer", text: "An emotional support burrito." },
    { id: "answer-037", type: "answer", text: "A thumbs up at the wrong time." },
    { id: "answer-038", type: "answer", text: "A glitter bomb." },
    { id: "answer-039", type: "answer", text: "Unholy amounts of ranch." },
    { id: "answer-040", type: "answer", text: "The group project dead weight." },
    { id: "answer-041", type: "answer", text: "A pirated copy of life." },
    { id: "answer-042", type: "answer", text: "Low battery anxiety." },
    { id: "answer-043", type: "answer", text: "A fake apology." },
    { id: "answer-044", type: "answer", text: "A mustache ride." },
    { id: "answer-045", type: "answer", text: "An inflatable hot tub." },
    { id: "answer-046", type: "answer", text: "A pigeon with attitude." },
    { id: "answer-047", type: "answer", text: "A broken fidget spinner." },
    { id: "answer-048", type: "answer", text: "The coworker who overshares." },
    { id: "answer-049", type: "answer", text: "A DMV line that never ends." },
    { id: "answer-050", type: "answer", text: "A knockoff smartwatch." },
    { id: "answer-051", type: "answer", text: "A dramatic reading of tweets." },
    { id: "answer-052", type: "answer", text: "A scarecrow with abs." },
    { id: "answer-053", type: "answer", text: "The ghost of dial-up internet." },
    { id: "answer-054", type: "answer", text: "An accidental reply-all." },
    { id: "answer-055", type: "answer", text: "A void where ambition used to be." },
    { id: "answer-056", type: "answer", text: "A midlife crisis scooter." },
    { id: "answer-057", type: "answer", text: "The algorithm judging you." },
    { id: "answer-058", type: "answer", text: "A lukewarm cup of coffee." },
    { id: "answer-059", type: "answer", text: "A suspiciously crunchy salad." },
    { id: "answer-060", type: "answer", text: "A feral house cat." },
    { id: "answer-061", type: "answer", text: "A parking ticket." },
    { id: "answer-062", type: "answer", text: "A wet sock." },
    { id: "answer-063", type: "answer", text: "The sound of chewing." },
    { id: "answer-064", type: "answer", text: "An unsolicited selfie." },
    { id: "answer-065", type: "answer", text: "A tiny parade." },
    { id: "answer-066", type: "answer", text: "An edible glitter smoothie." },
    { id: "answer-067", type: "answer", text: "A cryptic fortune cookie." },
    { id: "answer-068", type: "answer", text: "A cat video spiral." },
    { id: "answer-069", type: "answer", text: "A spontaneous conga line." },
    { id: "answer-070", type: "answer", text: "A cursed family recipe." },
    { id: "answer-071", type: "answer", text: "An empty fridge." },
    { id: "answer-072", type: "answer", text: "A nap that ruins your night." },
    { id: "answer-073", type: "answer", text: "A large ladle of shame." },
    { id: "answer-074", type: "answer", text: "A haunted mannequin." },
    { id: "answer-075", type: "answer", text: "A motivational poster that lies." },
    { id: "answer-076", type: "answer", text: "A duet with the neighbor's dog." },
    { id: "answer-077", type: "answer", text: "A pocket full of lint." },
    { id: "answer-078", type: "answer", text: "A cheap magic trick." },
    { id: "answer-079", type: "answer", text: "An overconfident GPS." },
    { id: "answer-080", type: "answer", text: "A rogue autocorrect." },
    { id: "answer-081", type: "answer", text: "A substitute teacher's power trip." },
    { id: "answer-082", type: "answer", text: "A karaoke mic that smells like beer." },
    { id: "answer-083", type: "answer", text: "A yoga pose gone wrong." },
    { id: "answer-084", type: "answer", text: "A surprise fire drill." },
    { id: "answer-085", type: "answer", text: "A half-eaten corn dog." },
    { id: "answer-086", type: "answer", text: "A rogue eyebrow hair." },
    { id: "answer-087", type: "answer", text: "A corporate wellness email." },
    { id: "answer-088", type: "answer", text: "A jump scare from a pop-up ad." },
    { id: "answer-089", type: "answer", text: "A toddler with markers." },
    { id: "answer-090", type: "answer", text: "A garage band reunion." },
    { id: "answer-091", type: "answer", text: "A pirate with allergies." },
    { id: "answer-092", type: "answer", text: "A salad that is mostly croutons." },
    { id: "answer-093", type: "answer", text: "A mismatched sock." },
    { id: "answer-094", type: "answer", text: "A slow internet connection." },
    { id: "answer-095", type: "answer", text: "A dramatic entrance nobody noticed." },
    { id: "answer-096", type: "answer", text: "A typo in a love letter." },
    { id: "answer-097", type: "answer", text: "A single Cheerio on the floor." },
    { id: "answer-098", type: "answer", text: "A sneeze you can't finish." },
    { id: "answer-099", type: "answer", text: "A very small inheritance." },
    { id: "answer-100", type: "answer", text: "A bold lie on a resume." }
];

export function createFakeAnswerDeck(): AnswerCard[] {
    return FAKE_ANSWER_CARDS;
}

export async function fetchFakeAnswerDeck(): Promise<AnswerCard[]> {
    return fisherYatesShuffle(createFakeAnswerDeck());
}